source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'STPUAllocationTracker_Example', :exclusive => true do
  pod "STPUAllocationTracker", :path => "../"
end

target 'STPUAllocationTracker_Tests', :exclusive => true do
  pod "STPUAllocationTracker", :path => "../"

  
end
